### DISCUSSION TITLE
My env is correct but I get dbt configuration is invalid : Parsing Error   Env var required but not provided: 'REDSHIFT_DB' from the linter.

### DISCUSSION THREAD

**Discussion by reyesjx7** [AltimateAI/vscode-dbt-power-user#1034] [Q&A] [answered]
Hi, I need help figuring out if there's a way to solve this issue.

I have my profiles.yml

```yaml
my_project:
  target: redshift #"{{ env_var('DBT_PROFILE')}}" # TODO: Change this to Jinja TARGET_PROFILE
  outputs:
    redshift:
      dbname: "{{ env_var('REDSHIFT_DB') }}"
      host: "{{ env_var('REDSHIFT_HOST') }}"
      password: "{{ env_var('REDSHIFT_PASSWORD') }}"
      port: "{{ env_var('REDSHIFT_PORT') | int }}"
      schema: "{{ env_var('REDSHIFT_SCHEMA') }}"
      threads: 4
      type: redshift
      user: "{{ env_var('REDSHIFT_USER')}}"
      ssl_mode: prefer
```

And I have the profile set to `my_project` in my dbt_project.yml.

I created all of the environment variables and have confirmed they're all there using printenv. The extension still highlight the entire file red because it says it can't find the environment variables.

Anyone have any solution for this?
