### ISSUE TITLE
Documentation editor mess up tests when same test exist with different configs

### ISSUE THREAD

**Issue by saravmajestic** [AltimateAI/vscode-dbt-power-user#1219]
### Expected behavior

- should preserve the tests as it is

### Actual behavior

- replaces config of tests

### Steps To Reproduce

I have two accepted values tests with two different configs but the Documentation Editor changed them to give them the same config.

#### before

       
```
tests:
          - accepted_values:
              values: ['deep_dish', 'detroit', 'thin_crust']
              config:
                severity: 'warn'
                where: "menu_item = 'pizza'"
          - accepted_values:
              values: ['gyro', 'sub', 'footlong']
              config:
                severity: 'warn'
                where: "menu_item = 'sandwich'"

```

#### after

```
- accepted_values:
              values:
                - deep_dish
                - detroit
                - thin_crust
              config: &a1
                severity: warn
                where: menu_item = 'pizza'
          - accepted_values:
              values:
                - gyro
                - sub
                - footlong
              config: *a1
```

### Operating System

MacOs

### dbt version

1.7

### dbt Adapter

any

### dbt Power User version

any

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!
