### ISSUE TITLE
Unable to run query for newly added source in yml

### ISSUE THREAD

**Issue by ndeunk** [AltimateAI/vscode-dbt-power-user#1274]
### Expected behavior

When I add a new source table to a project .yml file, I'd like to query it directly with dbt Power User.

### Actual behavior

I receive an error message:

Sql_Operation 'sql_operation.xxx.t_2cbf0bd27e1b4e17b63ec4ca11dce2ab' (from remote system.sql) depends on a source named 'xxx.yyy' which was not found

### Steps To Reproduce

1. Create .yml file in models directory (e.g. schema.yml)
2. Add entry under sources node: 

```
version: 2

sources:
  - name: bronze
    description: my test
    database: db_name
    schema: dbo

    tables:
      - name: my_test_table
```

3. Create new model file (.sql) and reference the newly created source
```
select * from {{ source('bronze', 'my_test_table') }}
```

4. Press CTRL+Enter to run a query for the newly created model

### Log output/Screenshots

Compilation Error
Sql_Operation 'sql_operation.xxx.t_2cbf0bd27e1b4e17b63ec4ca11dce2ab' (from remote system.sql) depends on a source named 'bronze.my_test_table' which was not found

### Operating System

Debian GNU/Linux 11 (bullseye)

### dbt version

1.8.3

### dbt Adapter

fabric (1.8.7)

### dbt Power User version

v0.41.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!
