### ISSUE TITLE
Model properties not displayed in preview

### ISSUE THREAD

**Issue by egononega** [AltimateAI/vscode-dbt-power-user#1370]
### Expected behavior

Preview should be the same as the compiled model test.sql when trying to display {{ model.meta }}

target\compiled\meta_tags\models\test.sql
{'project': 'YES', 'project_model': 'YES', 'schema': 'YES', 'model': 'YES'}

### Actual behavior

some properties are ignored by the preview.
The result of the preview is: 

models\test.sql (preview)
{'project': 'YES', 'model': 'YES'}

### Steps To Reproduce

schema.yml
``` YML
models:
  - name: test
    description: "A TEST dbt model"
    meta:
      schema: "YES"
```
Model test.sql
```SQL
{{
	config( 
    { "meta": { "model": "YES" }} 
  )
}}

{{ model.meta }}

{{ model.description }}
```
dbt_project.yml
``` YML
models:
  meta_tags:
    +meta:
      project: "YES"
    test:
      +meta:
        project_model: "YES"
```

model.discription is also missing from the preview, and displayed in the compiled query.

### Operating System

windows 11

### dbt version

1.8.4

### dbt Adapter

snowflake

### dbt Power User version

v0.44.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!
