### ISSUE TITLE
Extension not picking up env variables from .env file

### ISSUE THREAD

**Issue by rapha-pereira** [AltimateAI/vscode-dbt-power-user#1554]
### Expected behavior

To use our dbt core we simply execute a source command that gets all the variables in our .env file of the workspace and it runs perfectly, the extension should use them too as described [here](https://docs.myaltimate.com/setup/optConfig/#Environment%20variables%20through%C2%A0python.envFile) in the docs of the extension.

### Actual behavior

The extension doesn't pick up the variables in .env file and keeps returning the same error (image bellow).
Those env variables are necessary to find the profiles yml of our dbt project.

![Image](https://github.com/user-attachments/assets/6c792847-c308-40ff-a776-ccab13d36492)

### Steps To Reproduce

- Create a .env file in your project.
- Create an env variable called: `DBT_PROFILES_DIR`
- Open the project in VSCode
- Extension doesn't work.

Bellow is my .env file as a .txt

[env-example.txt](https://github.com/user-attachments/files/18481274/env-example.txt)

 for example.

### Operating System

WSL for Windows

### dbt version

1.7.18

### dbt Adapter

BigQuery

### dbt Power User version

0.51.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
@rapha-pereira  Have you looked at https://docs.myaltimate.com/setup/optConfig/#environment-variables-setup ?

**Comment by rapha-pereira** [comment]
> [@rapha-pereira](https://github.com/rapha-pereira) Have you looked at https://docs.myaltimate.com/setup/optConfig/#environment-variables-setup ?

Yes, and I tried the method via the settings.json file and it didn't work either.
My coworker tried using the extension and got the same error as me.

**Comment by anandgupta42** [comment]
@rapha-pereira Can you share the settings.json and sample .env file here?

**Comment by anandgupta42** [comment]
We rely on the Python VSCode extension to fetch the environment variables.

Check the section: https://docs.myaltimate.com/setup/optConfig/#environment-variables-through-pythonenvfile

Try manually setting the path for your .env file using the settings mentioned in the document above. Then run the [environment variable printer](https://docs.myaltimate.com/setup/optConfig/#listing-environment-variables-detected-by-the-extension) to check if the variable is detected.

Also, if you post it in the community Slack, someone may comment on it if they have solved it in the past - 
https://getdbt.slack.com/archives/C05KPDGRMDW

**Comment by rapha-pereira** [comment]
When printing the env variables, my `DBT_PROFILES_DIR` variable from _dotenv_ appears, but the extension fails to parse the project with the error image above.
e.g.: 
```
DBT_PROFILES_DIR=config            source:dotenv
DBT_PROJECT_DIR=/home/rapha-wsl/github-projects/my-dbt-project            source:dotenv
DBT_DATASET_DEFAULT=dw_test              source:dotenv
```

Why does dbt core in the terminal work fine with these variables and the extension doesn't? What am I missing here?

**Comment by rapha-pereira** [comment]
Another thing...
The extension works for builds and runs, only query preview and compiled dbt preview don't work.

**Comment by BeaAnjos** [comment]
Up! I'm having the same issue!

**Comment by diegoquintanav** [comment]
if `DBT_PROFILES_DIR` is set, then

https://github.com/AltimateAI/vscode-dbt-power-user/blob/5735fa6e8f1ce3cbc2bb2b2d6f4a062baa2bf254/dbt_core_integration.py#L220

is joining `project_dir` with `profiles_dir`. If `project_dir` is coming from `DBT_PROJECT_DIR`, and both paths are relative then this is effectively producing `<DBT_PROJECT_DIR>/<DBT_PROFILES_DIR>` which may not exist.

In my case, I have

```
DBT_PROJECT_DIR=my_project
DBT_PROFILES_DIR=my_project/my_profiles
```

and this method is returning `default_profiles_dir=my_project/my_project/my_profiles`

The value of `project_dir` being passed is resolved as `**/dbt_project.yml` as in https://github.com/AltimateAI/vscode-dbt-power-user/blob/5735fa6e8f1ce3cbc2bb2b2d6f4a062baa2bf254/src/manifest/dbtWorkspaceFolder.ts#L90


Finall, I don't see any references to `DBT_PROJECT_DIR` in the code, maybe that's related to the issue?

**Comment by rapha-pereira** [comment]
Loved the PR @diegoquintanav!
Just a note here: the main issue is that the extension doesn't replicate the way that dbt core handles environment variables, even though it should, as explained in the documentation. dbt runs normally with my environment variables, but the extension doesn't.

**Comment by mdesmet** [comment]
@rapha-pereira : can you clarify in which way the extension doesn't handle environment variables as dbt 
core ?

**Comment by rapha-pereira** [comment]
> @rapha-pereira : can you clarify in which way the extension doesn't handle environment variables as dbt 
> core ?

dbt Core runs fine with DBT_PROFILES_DIR set, but the dbt Power User extension doesn't seem to recognize it, as I detailed in my comments above.

**Comment by rapha-pereira** [comment]
Any updates here, guys?!

**Comment by mdesmet** [comment]
So your profiles dir is in the root of your workspace root, called `config` or is it in another subfolder? It is true that we don't support `DBT_PROJECT_DIR` but that shouldn't impact the behavior of a relative path in `DBT_PROFILES`)_DIR, it should be relative to your workspace root.

**Comment by rapha-pereira** [comment]
No. My DBT_PROFILES_DIR variable points to "config". "config" is a folder in the root of our project that contains "profile.yml" file.
My "DBT_PROFILE" variable points to a profile named "local".
Inside our "profile.yml" there is a target called "local" that is the profile.

Example:
**.env**
```
DBT_PROFILE=local
DBT_PROFILES_DIR=config
DBT_DATASET_DEFAULT=people_dw_test
```
**config/profiles.yml**
```
bigquery-people:
  outputs:
    prod:
      type: bigquery
      method: oauth
      project: my-project
      dataset: "{{  env_var('DBT_DATASET_DEFAULT')  }}"
      threads: 4
      timeout_seconds: 300
      priority: interactive
    nonprod:
      type: bigquery
      method: oauth
      project: my-project
      dataset: "{{  env_var('DBT_DATASET_DEFAULT')  }}"
      threads: 4
      timeout_seconds: 300
      priority: interactive
    local:
      type: bigquery
      method: service-account
      project: my-project
      dataset: "{{  env_var('DBT_DATASET_DEFAULT')  }}"
      keyfile: application_default_credentials.json
      threads: 4
      timeout_seconds: 300
      priority: interactive
    dev:
      type: bigquery
      method: oauth
      project: my-project
      dataset: "{{  env_var('DBT_DATASET_DEFAULT')  }}"
      threads: 4
      timeout_seconds: 300
      priority: interactive

  target: "{{  env_var('DBT_PROFILE')  }}"
```
> I masked the project to "my-project".

dbt-core runs fine with those variables, files and project structure, the extension don't.
