### ISSUE TITLE
data_tests using dbt_utils.unique_combination_of_columns are duplicated under tests section

### ISSUE THREAD

**Issue by novellino** [AltimateAI/vscode-dbt-power-user#1585]
### Expected behavior

When defining a model with `data_tests` that uses `dbt_utils.unique_combination_of_columns`, the extension incorrectly duplicates these tests by adding them again under the tests section of the model.
Steps to Reproduce:

Create a dbt model with the following configuration:

```yml
models:
  - name: orders
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - country_code
            - order_id
```

1. The test should only appear once under the `data_tests` section as defined in the original configuration.

2. When adding or modifying column definitions to the model, the `data_tests` section should remain unchanged. For example, adding column definitions like this:

```yml
models:
  - name: orders
    columns:
      - name: order_id
        description: "Primary key for orders"
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - country_code
            - order_id
```

### Actual behavior

The test is duplicated, appearing both under `data_tests` and `tests` sections:

```yml
models:
  - name: orders
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - country_code
            - order_id
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - country_code
            - order_id
```

### Steps To Reproduce

1. Add the following model configuration to the YAML file:

```yml
models:
  - name: orders
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - country_code
            - order_id
```

2. Save the file
3. Add a column definition to the model (trigger the issue):

```
models:
  - name: orders
    columns:
      - name: order_id
        description: "Primary key for orders"
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - country_code
            - order_id
```
4. Save the file
5. The test is duplicated, appearing both under `data_tests` and `tests` sections.

### Log output/Screenshots

dbt compile

Encountered an error: Parsing Error 
Invalid test config: cannot have both 'tests' and 'data_tests' defined

### Operating System

Windows 11

### dbt version

1.8.8

### dbt Adapter

dbt-oracle

### dbt Power User version

0.54.0

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!
