### ISSUE TITLE
Parse yaml values when generating dbt model from source definition

### ISSUE THREAD

**Issue by romain-bury** [AltimateAI/vscode-dbt-power-user#350]
### Expected behavior

I have a very simple .yml file describing the sources I use, structured like this : 
````
version: 2

sources:
  - name: sources
    database: "{{ target.project }}"
    tables:
      - name: clients
      - name: invoices
````

When i click on "generate model" (from DBT Power User) under each table, i get a 400 Error, saying that "{{ target.project }} " is not found. I believe that DBT Power User fails to interpret the Jinja script for the database variable. 

### Actual behavior

400 Error, detailed below. 

### Steps To Reproduce

n/a

### Log output/Screenshots

An error occured while trying to generate the model 400 GET https://bigquery.googleapis.com/bigquery/v2/projects/%22%7B%7B%20target.project%20%7D%7D%22/datasets/rb/tables/invoices?prettyPrint=false: Invalid resource name projects/"{{ target.project }}"; Project id: "{{ target.project }}"

### Operating System

WSL 2 Ubuntu 

### dbt version

1.2.4

### dbt Adapter

BigQuery

### dbt Power User version

Latest

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!
