### ISSUE TITLE
add support for YAML block notation in model descriptions

### ISSUE THREAD

**Issue by brandonpeebles** [AltimateAI/vscode-dbt-power-user#568]
The current documentation editor is great, but it seems to overwrite any YAML block notation you might have in the file. It forces the description string to begin immediately after `description: `.  I've noticed that if I include headings in markdonw, then it will add `>-`, but I'd prefer to have a predictable behavior.

Can we add better support to either leave the `|` or `>` characters if they are there, or allow the user to specify which format they'd prefer as default?
https://github.com/innoverio/vscode-dbt-power-user/blob/873424125bbb35f2f30fcc905a9f2341c1307eb4/docs_edit_panel/main.js#L29

For instance, I like to use `|` and then have VSCode wrap my YAML lines for me (while still leaving them on the same actual code line). This way I can easily write plain markdown descriptions like below:
```yaml
models:
- name: my_model
   description: |
     # Overview:
     Some basic description here

     # Note:
     Some additional info or perhaps warnings about the code here
```
