### ISSUE TITLE
vs-code-power-user : documentation editor case sensitivity issue with sync columns with database

### ISSUE THREAD

**Issue by geoff-rathmell** [AltimateAI/vscode-dbt-power-user#595]
### Expected behavior

The documentation editor "synchronize columns with database" feature should correctly match field names regardless of case-sensitivity. 

### Actual behavior

The synchronize columns with database feature in the documentation editor seems to be case-sensitive and causes issues if an existing yaml document with lower-case field names is synchronized, the doc editor ignores the existing content (description) and adds the field as UPPER as if it were new.

### Steps To Reproduce

create yaml model definition file with field and description

```
models:
  - name: int_table_subtotal
    description: subtotals
    columns:
      - name: myfield
        description: my awesome description
```

Use the documentation editor to edit this model.

When you re-sync the columns, the 'myfield' details will get wiped out and replaced with blank 'MYFIELD' column info.

### Operating System

windows 10

### dbt version

core 1.5.4

### dbt Adapter

snowflake 1.5.2

### dbt Power User version

v0.17.9

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!
