### ISSUE TITLE
Documentation Editor Overwrites Existing Documentation if not re-written

### ISSUE THREAD

**Issue by amakalin4** [AltimateAI/vscode-dbt-power-user#618]
### Expected behavior

Let's say I have the following YML file to start:

Before:
```
  columns:
  - name: ID
    description: unique identifier
    tests:
    - not_null
    - unique
  - name: Value
    description: value of the row
  - name: Notes
    description: none
```

I have no `Notes` description so I'd like to use `Documentation Editor` to update just that field; therefore, I go into the editor and type in my new description for the `Notes` field only to get the following updated YML file:

After:
```
  columns:
  - name: ID
    description: unique identifier
    tests:
    - not_null
    - unique
  - name: Value
    description: value of the row
  - name: Notes
    description: added notes by the user
```

### Actual behavior

`Documentation Editor` as it stands does not pull in existing definitions; therefore, if I update only the `Notes` description in the editor, I will instead get the following result:

After:
```
  columns:
  - name: ID
    description: ""
  - name: Value
    description: ""
  - name: Notes
    description: added notes by the user
```

Unless I specifically re-copy the definitions of all other fields in the `Documentation Editor` session, they will be overwritten with blanks - additionally, my tests will also be overwritten.

Ideally, the `Documentation Editor` UI would pull in the existing documentation and testing of existing models so that they do not need to be overwritten each time you want to make an update.

### Steps To Reproduce

1. Write documentation for any model in `Documentation Editor`, filling in description for all fields
2. Save
3. Go back into `Documentation Editor` and update the descriptions of only a couple of fields
4. Save into existing file
5. After this save, only the descriptions of the fields updated in 3) will remain

### Operating System

macOS Monterey 12.5.1

### dbt version

1.3.1

### dbt Adapter

Not sure

### dbt Power User version

v0.17.7

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!
