### ISSUE TITLE
`Generate model` outputs duplicate columns for identically-structured data sources

### ISSUE THREAD

**Issue by cmcnicoll** [AltimateAI/vscode-dbt-power-user#795]
### Expected behavior

```
with
    source as (select * from {{ source("schema1", "table1") }}),
    renamed as (
        select
            {{ adapter.quote("column1") }},
            {{ adapter.quote("column2") }},
            {{ adapter.quote("column3") }}
        from source
    )
select *
from renamed
```

### Actual behavior

```
with
    source as (select * from {{ source("schema1", "table1") }}),
    renamed as (
        select
            {{ adapter.quote("column1") }},
            {{ adapter.quote("column1") }},
            {{ adapter.quote("column2") }},
            {{ adapter.quote("column2") }},
            {{ adapter.quote("column3") }},
            {{ adapter.quote("column3") }}
        from source
    )
select *
from renamed
```

### Steps To Reproduce

1. Click on `Generate model` for `table1` in the following example:

`_union__sources.yml`
```
version: 2

sources:
  - name: schema1
    database: skynet
    tables: &tables
      - name: table1
      - name: table2
      - name: table3

  - name: schema2
    database: skynet
    tables: *tables
```

### Log output/Screenshots

I think this is caused by identically-structured data sources that must be unioned before the `base` model.

`union__table1.sql`
```
select *
from {{ source("schema1", "table1") }}
union all
select *
from {{ source("schema2", "table1") }}
```

`base__table1.sql`
```
with
    source as (select * from {{ ref("union__table1") }}),
    renamed as (
        select
            {{ adapter.quote("column1") }},
            {{ adapter.quote("column2") }},
            {{ adapter.quote("column3") }}
        from source
    )
select *
from renamed
```

### Operating System

Windows 11 Pro

### dbt version

1.7.4

### dbt Adapter

Redshift

### dbt Power User version

0.28.4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!
