### ISSUE TITLE
Model versions are not visible in new UX lineage graph

### ISSUE THREAD

**Issue by wkrill** [AltimateAI/vscode-dbt-power-user#872]
### Expected behavior
When having multiple versions of a model I expect to see the version number (v1, v2, ...) in the lineage graph like we do in the old lineage graph:

![image](https://github.com/AltimateAI/vscode-dbt-power-user/assets/24196461/54d2c8ea-1398-4c70-8474-371d9ed38209)

### Actual behavior
The different versions are indistinguishable:
![image](https://github.com/AltimateAI/vscode-dbt-power-user/assets/24196461/eabd6864-75b4-417f-be3e-1c9e73aabb50)

### Steps To Reproduce
Models used to produce screenshots:
```SQL
-- my_model_base.sql
select 1 as field_a, 2 as field_b
```

```SQL
-- my_model_v1.sql
select field_a from {{ ref("my_model_base") }}
```

```SQL
-- my_model_v2
select field_a, field_b from {{ ref("my_model_base") }}
```

```yaml
# schema.yml
version: 2

models:
  - name: my_model
    latest_version: 2
    versions:
      - v: 2
        columns:
          - name: field_a
          - name: field_b
      - v: 1
        columns:
          - name: field_a
```
### Operating System
Ubuntu 22.04.2 LTS
### dbt version
1.7.2
### dbt Adapter
Postgres
### dbt Power User version
v0.30.1
### Are you willing to submit PR?
- [ ] Yes I am willing to submit a PR!
